### ISSUE TITLE
How to edit level tower in battle?

### ISSUE THREAD

**Issue by HyperCrack** [retroroyale/ClashRoyale#5]
can you tell me how to edit level tower in battle please...

**Comment by zzVertigo** [comment]
The health for towers looks to be located here: https://github.com/retroroyale/ClashRoyale/blob/master/ClashRoyale/ClashRoyale/Protocol/Messages/Server/SectorStateMessage.cs#L291-L303

Someone can correct me.

^^

**Comment by HyperCrack** [comment]
Thanks you.. Can you create me level 8 tower please, because in me force close

**Comment by kyledoescode** [comment]
He might mean king level. If so, that's easy, just edit the int on this line. 

However, it will not update tower HP (like in the real game) because as @zzVertigo pointed out, the values are currently hard-coded in the SectorState packet. ;)

https://github.com/retroroyale/ClashRoyale/blob/master/ClashRoyale/ClashRoyale/Logic/Home/Home.cs#L37
